[build]
  publish = "."
  command = ""

# Expose secret to Edge (needed for cookie verification)
[edge_functions]
  environment = ["MH_SESSION_SECRET"]

[[edge_functions]]
  function = "auth"
  path = "/*"

# Map login API to the function (before SPA fallback)
[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/invite"
  status = 200
  force = true

# SPA fallback LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
