# netlify.toml

[build]
  publish = "."
  command = ""

# Register the Edge auth gate AND pass env to it (all in one block)
[[edge_functions]]
  function = "auth"
  path = "/*"
  environment = ["MH_SESSION_SECRET"]

# Route the login POST to your Netlify Function (must be BEFORE SPA fallback)
[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/invite"
  status = 200
  force = true

# SPA fallback — keep LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
