# netlify.toml  — minimal, parse-safe

[build]
  # If your built site lives in "dist" or "build", change this path.
  publish = "."
  command = ""

# Global Edge settings (this is where 'environment' goes)
[edge_functions]
  environment = ["MH_SESSION_SECRET"]

# Register the Edge auth gate (your file: netlify/edge-functions/auth.ts)
[[edge_functions]]
  function = "auth"
  path = "/*"

# Map the login API to your Function (must be BEFORE SPA fallback)
[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/invite"
  status = 200
  force = true

# SPA fallback — keep LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
