# netlify.toml  (UTF-8, straight quotes)

[build]
  publish = "."
  command = ""

# Global settings for Edge Functions
# (this is where 'environment' goes)
[edge_functions]
  environment = ["MH_SESSION_SECRET"]

# Register your Edge auth function
[[edge_functions]]
  function = "auth"
  path = "/*"

# Route the login POST to your Netlify Function (must be BEFORE SPA fallback)
[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/invite"
  status = 200
  force = true

# SPA fallback — keep LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
