# netlify.toml

[build]
  publish = "."
  command = ""

# Make MH_SESSION_SECRET available to Edge Functions
[edge_functions]
  environment = ["MH_SESSION_SECRET"]

# Register the Edge auth gate on all routes
[[edge_functions]]
  function = "auth"
  path = "/*"

# Route the login POST to your Netlify Function (must be BEFORE SPA fallback)
[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/invite"
  status = 200
  force = true

# SPA fallback — keep LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
