[build]
  publish = "."
  command = ""

# Make MH_SESSION_SECRET available to Edge Functions
[edge_functions]
  environment = ["MH_SESSION_SECRET"]

[[edge_functions]]
  function = "auth"
  path = "/*"

# Map login to your function (keep before SPA fallback)
[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/invite"
  status = 200
  force = true

# SPA fallback LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
