[build]
  publish = "."
  command = ""

# --- Edge function that guards private routes ---
[[edge_functions]]
  function = "auth"
  path = "/*"

# --- Map your login POST to the Netlify Function (must be BEFORE SPA fallback) ---
[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/invite"
  status = 200
  force = true

# --- SPA fallback (keep LAST) ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
