# netlify.toml

[build]
  publish = "."
  command = ""

# Register the Edge auth gate
[[edge_functions]]
  function = "auth"
  path = "/*"

# Map login API to your Function (keep BEFORE SPA fallback)
[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/invite"
  status = 200
  force = true

# SPA fallback — keep LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
